name: phone_store
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_login: ^5.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.0
  flutter_custom_selector: ^0.0.3
  firebase_app_check: ^0.3.2+3
  collection: ^1.18.0
  shared_preferences: ^2.5.2
  google_sign_in: ^6.2.2
  email_auth: ^2.0.0
  email_otp: ^3.0.2
  mailer: ^6.4.1
  card_swiper: ^3.0.1
  uuid: ^4.5.1
  intl_phone_field: ^3.2.0
  flutter_stripe: ^9.2.0
  http: ^1.4.0
  flutter_phone_direct_caller: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true
  ios: true
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/img/
    - assets/fonts/
    - assets/logo/
  uses-material-design: true

  fonts:
    - family: Sniglet
      fonts:
        - asset: assets/fonts/Sniglet/Sniglet-ExtraBold.ttf
        - asset: assets/fonts/Sniglet/Sniglet-Regular.ttf
          weight: 400
